import { Link, useRouterState } from '@tanstack/react-router';
import { Bell, Cloud, CloudRain, Database, Home, LayoutDashboard, Menu, Radar, Settings, X, Zap } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { useWeather } from './WeatherContext';
const nav = [{ to: '/', label: 'Overview', icon: Home }, { to: '/live-map', label: 'Live Map', icon: Radar }, { to: '/forecast', label: 'Forecast', icon: CloudRain }, { to: '/alerts', label: 'Alerts', icon: Bell }, { to: '/data-sources', label: 'Data Sources', icon: Database }, { to: '/settings', label: 'Settings', icon: Settings }] as const;
export function Shell({ children }: { children: ReactNode }) {
  const path = useRouterState({ select: s => s.location.pathname });
  const { alerts, settings } = useWeather();
  const [mobileOpen, setMobileOpen] = useState(false);
  return <div className={`app-shell ${settings.compact ? "compact-display" : ""}`}><header className="topbar"><Button variant="ghost" size="icon" className="mobile-menu" title="Open menu" onClick={() => setMobileOpen(true)}><Menu /></Button><Link to="/" className="brand"><span className="brand-symbol"><Cloud /><Zap /></span><span><strong>ThunderCast AI</strong><small>AI/ML Based Nowcasting of Thunderstorm & Lightning</small></span></Link><div className="top-data"><span>Multi-Radar</span><i /><span>Satellite</span><i /><span>Lightning</span><i /><span>Model Data</span></div><div className="top-status"><span>Mon, 26 May 2025 14:32 IST</span><small><i /> Simulated data</small></div></header><div className="app-body"><aside className={`sidebar ${mobileOpen ? 'sidebar-open' : ''}`}><div className="mobile-sidebar-head"><strong>Navigation</strong><Button variant="ghost" size="icon" title="Close menu" onClick={() => setMobileOpen(false)}><X /></Button></div><nav>{nav.map(item => <Link to={item.to} key={item.to} className={`nav-item ${path === item.to ? 'active' : ''}`} onClick={() => setMobileOpen(false)}><item.icon size={18} /><span>{item.label}</span>{item.label === 'Alerts' && alerts.filter(a => a.status === 'Active').length > 0 && <b>{alerts.filter(a => a.status === 'Active').length}</b>}</Link>)}</nav><div className="sidebar-foot"><LayoutDashboard size={14} /> OPERATIONS CENTER</div></aside><main className="main-content">{children}</main></div>{mobileOpen && <div className="sidebar-backdrop" onClick={() => setMobileOpen(false)} />}</div>;
}
