/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as LiveMapRouteImport } from './routes/live-map'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMapRoute = LiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/data-sources': typeof DataSourcesRoute
  '/forecast': typeof ForecastRoute
  '/live-map': typeof LiveMapRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/data-sources': typeof DataSourcesRoute
  '/forecast': typeof ForecastRoute
  '/live-map': typeof LiveMapRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/data-sources': typeof DataSourcesRoute
  '/forecast': typeof ForecastRoute
  '/live-map': typeof LiveMapRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/alerts' | '/data-sources' | '/forecast' | '/live-map' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/alerts' | '/data-sources' | '/forecast' | '/live-map' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/data-sources'
    | '/forecast'
    | '/live-map'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DataSourcesRoute: typeof DataSourcesRoute
  ForecastRoute: typeof ForecastRoute
  LiveMapRoute: typeof LiveMapRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-map': {
      id: '/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof LiveMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DataSourcesRoute: DataSourcesRoute,
  ForecastRoute: ForecastRoute,
  LiveMapRoute: LiveMapRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
